version: '2'

services:

### PostgreSQL Container (Master) ####################################

  master:
    restart: always
    build: ./master
    volumes:
      - master:/var/lib/postgresql
    ports:
      - "5434:5434"
    environment:
      - DEBUG=false
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=dbname
      - DB_UNACCENT=false
      - REPLICATION_MODE=master
      - REPLICATION_USER=replicator
      - REPLICATION_PASS=replpassword
      - REPLICATION_SSLMODE=

### PostgreSQL Container (Slave) ####################################

  slave:
    restart: always
    build: ./slave
    volumes:
      - slave:/var/lib/postgresql
    ports:
      - "5435:5435"
    links:
      - master:master
    environment:
      - DEBUG=false
      - REPLICATION_MODE=slave
      - REPLICATION_HOST=master
      - REPLICATION_USER=replicator
      - REPLICATION_PASS=replpassword


### Volumes Setup ###########################################

volumes:
  master:
    driver: "local"
  slave:
    driver: "local"
  sessions:  ## nothing is connected to this (- ./data/sessions:/sessions)
    driver: "local"
