version: '2'

services:

### PostgreSQL Container (Master) ####################################

  master:
    restart: always
    build: ./master
    volumes:
      - master:/var/lib/postgresql
    ports:
      - "5434:5434"
    environment:
      - DEBUG=false
      - DB_USER=zeroc0d3_user
      - DB_PASS=zeroc0d3_password
      - DB_NAME=zeroc0d3_dbname
      - DB_UNACCENT=false
      - REPLICATION_MODE=master
      - REPLICATION_USER=replicator
      - REPLICATION_PASS=replpassword
      - REPLICATION_SSLMODE=
### PostgreSQL Container (Slave) ####################################

  slave1:
    restart: always
    build: ./slave
    volumes:
      - slave1:/var/lib/postgresql
    ports:
      - "5435:5435"
    links:
      - master:master
    environment:
      - DEBUG=false
      - REPLICATION_MODE=slave
      - REPLICATION_HOST=master
      - REPLICATION_USER=replicator
      - REPLICATION_PASS=replpassword

### PostgreSQL Container (Slave) ####################################

  slave2:
    restart: always
    build: ./slave
    volumes:
      - slave2:/var/lib/postgresql
    ports:
      - "5436:5436"
    links:
      - master:master
    environment:
      - DEBUG=false
      - REPLICATION_MODE=slave
      - REPLICATION_HOST=master
      - REPLICATION_USER=replicator
      - REPLICATION_PASS=replpassword


### Volumes Setup ###########################################

volumes:
  master:
    driver: "local"
  slave1:
    driver: "local"
  slave2:
      driver: "local"
  sessions:  ## nothing is connected to this (- ./data/sessions:/sessions)
    driver: "local"
